### ISSUE TITLE
Leak de consumidores

### ISSUE THREAD

**Issue by tkrafael** [fabiogalante/Bemobi.FileMonitoring#1]
https://github.com/fabiogalante/Bemobi.FileMonitoring/blob/9ea1ebf8b9e7fd1116bdc8b3d24c6b6d5160a22c/FileMonitoring/Worker.cs#L32

Se eu entendi bem, a aplicação fica registrando um novo consumidor a cada 1000ms. Esse processo foi algo esperado?

**Comment by fabiogalante** [comment]
Não seria registrar, ele consulta o Rabbit a cada 1000ms, é um BackgroundService.

**Comment by tkrafael** [comment]
Segundo a documentação (https://www.rabbitmq.com/tutorials/tutorial-two-java.html) (está em java, mas as assinaturas e consequentemente as implementações são próximas), o método basicConsume registra um consumidor e só precisa ser chamado uma vez. O protocolo do rabbitmq (diferente por exemplo do SQS) usa o modelo push, onde o simples fato de a aplicação estar conectada faz com que ela seja notificada sobre novas mensagens, sem necessitar de fazer polling e executar comandos "pull".

No caso do SQS, por exemplo, é necessário solicitar um batch de mensagens em um loop. Esse é o modelo pull. E especificamente no caso do SQS, isso ocorre principalmente devido a AWS cobrar por requests e não por mensagens.
